### ISSUE TITLE
Add button to unsubscribe in the issue page

### ISSUE THREAD

**Issue by fernandog** [Daskiworks/ghwatch#106]
As title.
I can only close.

**Comment by velias** [comment]
Hi, gh::watch app does not contain any issue page. It opens details related to the notification into browser or other github app (eg. Octodroid) you have in your phone. 
Or do I misunderstand your request?  Try to provide better explanation please.

**Comment by fernandog** [comment]
@velias 

I can reopen but I can't unsubscribe

![screenshot_20171122-180905](https://user-images.githubusercontent.com/2620870/33147829-86551988-cfb0-11e7-9974-11b52deee36a.jpg)

**Comment by velias** [comment]
Thanks. This screen is not from ghwatch, it is from other app, looks like OctoDroid. So I can't modify it.

**Comment by fernandog** [comment]
Oh ok. Sorry. As it opened from your app I made a mistake. Sorry

**Comment by velias** [comment]
No problem. This smooth integration of different apps is really nice feature of the Android platform 😀
