### ISSUE TITLE
Allow to show all notifications (not unread only) with meaningful filtering

### ISSUE THREAD

**Issue by velias** [Daskiworks/ghwatch#11]
Allow to show all notifications (not unread only) with meaningful filtering:
- by time in history - last day, week, month
- by repository
- by notification type (Issue, Commit, Pull Request, ...)
- by participating flag

We have to use some time based filter all the time not to hurt GitHub API by too much notifications in response.

**Comment by laughedelic** [comment]
Wouldn't it make sense to store all new notifications you receive for this feature? Then you don't need to worry about Github API limits..

**Comment by velias** [comment]
I'm probably not going to implement this feature, there are other apps which provide this. I have limited time so I am focusing to keep the users in touch with the good level of new notifications handling which is not available in other apps.
