### ISSUE TITLE
Not receiving Android notifications

### ISSUE THREAD

**Issue by taylorthurlow** [Daskiworks/ghwatch#116]
I'm on a Pixel 3XL, latest version of Android P. I've made sure that the app itself is allowed to send notifications. Suggestions?

**Comment by velias** [comment]
Hi. I looked into Play Dev console and analytics, but no any error there. I see four pixel 3xl users, and nearly 50% of users is o Android P. I have report about this problem only from you, it is hard to debug 🤔 Do you have your phone alone, or do you for example have some Wear device linked to it?

**Comment by velias** [comment]
Btw did you look at this note about notification related permissions on github? https://github.com/Daskiworks/ghwatch/blob/master/README.md#notifications-from-github-private-repositories

**Comment by velias** [comment]
I hope you looked into Settings > GitHub Api Call info and you see there that api calls are performed

**Comment by taylorthurlow** [comment]
I have no Wear device. I checked out the note about GitHub permissions - the notifications I'm not receiving are for public repositories. I've checked the API call info section and API calls are being made properly. The issue isn't that your application isn't receiving notifications from GitHub, it's that Android itself is not display notifications from your application.

**Comment by velias** [comment]
Thanks for all the info. I'm going to do some tests and debugging, hopefully it will be successful to patch this problem

**Comment by InvisibleSymbol** [comment]
I just wanted to add that I am having the same problem. Repository is public, I am seeing that I got notifications on the website and on the overview in the app, but just don't get any notifications. Even Android reports that the app hasn't ever send anything: https://imgur.com/2SbKbhl
I'm on a custom rom, but it's Android P, or at least a preview of it. https://imgur.com/DZUSCBR

**Comment by taylorthurlow** [comment]
I have the same notification report as @InvisibleSymbol does in the first linked image.

**Comment by velias** [comment]
Sorry guys, bug is patched, I'm going to release new version.

**Comment by taylorthurlow** [comment]
@velias I hate to say it but it seems like I'm having this exact same problem again. API calls look like they're still working as intended, but I'm not sure what else to check/look at.

**Comment by velias** [comment]
Strange, try to look into Android settings > Notifications, find GH::watch app and check that notifications are enabled there (both for whole app and for category. "GitHub notifications" )

**Comment by InvisibleSymbol** [comment]
FYI, I can confirm that it has been working for me with the latest release.

**Comment by taylorthurlow** [comment]
I went in and toggled every relevant setting off and on last night and they started working again this morning. No idea. 

Thanks anyways!
