### ISSUE TITLE
[Enhancement]More notification control

### ISSUE THREAD

**Issue by Alpvax** [Daskiworks/ghwatch#121]
I am subscribed to several quite active repo's, so have set the android notifications to only display for participating issues.

What I would like is to always have notifications for my own repo's, but participating for others'.

One potentially useful feature would be being able to set rules on a per repo basis, but I would be happy with just mine vs others.

**Comment by velias** [comment]
You can go to "watched repositories" view, and set "notification filter" for each repo there (using dot menu). Isn't it what you need?

**Comment by Alpvax** [comment]
I still want to receive notifications for all of them in the app, but I only want to receive system notifications for certain repo's

**Comment by velias** [comment]
It works this way. You will see all notifications from the repo in the app, but only those matching given filter will fire android system notification.

**Comment by velias** [comment]
There is second setting "Repository visibility" which allows you to hide notifications from the repo in the app but still watch it on the github.

**Comment by Alpvax** [comment]
Thanks for letting me know that was there!

**Comment by Alpvax** [comment]
One of my watched repo's is not in that list, is there any way to force a refresh?

**Comment by velias** [comment]
Pull to refresh works. It may be also matter of permission on github, please look into Readme on github for description
