### ISSUE TITLE
Add wearable features to android notifications

### ISSUE THREAD

**Issue by velias** [Daskiworks/ghwatch#41]
Review how android notifications provided by this app look like on wearable device and improve it if possible - https://developer.android.com/training/wearables/notifications/index.html

**Comment by velias** [comment]
This should be resolved for Nougat+ devices thanks to Bundled notifications implemented in #84, but it should be tested to prove it as available doc is not very clear.

**Comment by laughedelic** [comment]
I'm a Pebble watch user, it's not a true Android Wear, but if those actions work for Android Wear, it usually also works for Pebble.
Currently I don't see any notification actions on my watch.

**Comment by velias** [comment]
Doc around notifications on wearable https://developer.android.com/training/wearables/notifications/index.html

**Comment by velias** [comment]
My friend who owns Android Wear 2 watches confirmed me that Bundled notifications and actions available in them work correctly there.

**Comment by velias** [comment]
@laughedelic do you know about some good docs for Pebble vs. android notifications - how it process notifications, where it takes actions from etc? Is it possible that Pebble does not take default notification actions, but uses only those added over `WearableExtender`? I should add them if I'll be somehow sure it will help you, but I do not have any chance to test it so at least some docs which supports this possibility should be good.
