### ISSUE TITLE
Upgrade to the Material design

### ISSUE THREAD

**Issue by velias** [Daskiworks/ghwatch#46]
App should be updated to the Material design - http://developer.android.com/design/material/index.html.
What it exactly mean for the app?:
- hide action bar when scrolling list of notifications on phones to get a bit bigger area for list
- change overlay action icons (from square dots to rounded dots one)
- change navigation drawer related indicators and it's behaviour (animation)
- change list of notifications to use card view instead of list view (I'm really not sure about this due space limitation and two column view on tablets)?
- widget design to match material design ones, but should allow to stay with old design also

ToDo something other?

**Comment by FezVrasta** [comment]
The cards list is discouraged by material design specifications, better a list control.

**Comment by jancborchardt** [comment]
Yeah, a cards view would also just be strange there. It’s a list of issues, so no real use for cards since the only real content is the title (no big image except the repo icon).

**Comment by Bluscream** [comment]
Does this also mean there will be a dark version available? I mean usually you don't spend that much time on the apps main screen or settings but the flash can really annoy all the time :o

**Comment by velias** [comment]
@Bluscream I created separate issue #90 for the dark theme. I want to release Material design ASAP to get some feedback, then I can play with the dark theme.

**Comment by velias** [comment]
Looks like I'm done with the coding, we will see from the users feedback. I have to prepare Play Store listing refresh (new images) before release.
