### ISSUE TITLE
Add color bar to indicate status of ticket

### ISSUE THREAD

**Issue by jancborchardt** [Daskiworks/ghwatch#57]
When issues are closed or pull reuests are merged, I often don't even need to look at them. It would be cool to have an indicator of the status of the ticket without needing to open it. The colors Github already uses are:

* green: issue/PR open
* red issue/PR closed
* purple: PR merged

It would be good to have e.g. a 3px colored bar on the left of each row.

**Comment by rvraghav93** [comment]
Any update on this?

**Comment by fernandog** [comment]
+1

**Comment by velias** [comment]
No any change unfortunatelly, still waiting for GitHub API change :-(

**Comment by fernandog** [comment]
@velias 

v3 has "state" and "labels". Can you implement then? thanks!!

https://developer.github.com/v3/issues/#list-issues

```
Response

Status: 200 OK
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4999
{
  "id": 1,
  "url": "https://api.github.com/repos/octocat/Hello-World/issues/1347",
  "labels_url": "https://api.github.com/repos/octocat/Hello-World/issues/1347/labels{/name}",
  "comments_url": "https://api.github.com/repos/octocat/Hello-World/issues/1347/comments",
  "events_url": "https://api.github.com/repos/octocat/Hello-World/issues/1347/events",
  "html_url": "https://github.com/octocat/Hello-World/issues/1347",
  "number": 1347,
  "state": "open",
```

**Comment by velias** [comment]
But this mean to do other request to get this info for each notification, which means more battery and data consumption.

**Comment by fernandog** [comment]
Why other request? You will only list issues once isnt?

And also can make a option default off.
Im sure users wont bother. Its plain text.

**Comment by velias** [comment]
I do not list issues, but notifications for the app. And necessary info is not present in notification API. You are right that config option together with lazy loading after app is open should work

**Comment by fernandog** [comment]
Thanks! I have almost 100 notifications at say in my organization. And lots of moderators.
It's too bad open issues that are already closed by the others.

**Comment by velias** [comment]
I finally implemented this feature using API workaround. Extra API call is performed for each notification to get status. Feature may be enabled/disabled in preferences as it may consume more resources (network bandwith and battery). 
And finally, I decided to provide this feature as a gift to peoples who make donation to support app development. Hope it is not a big problem for you, the donation is not any high value.

**Comment by fernandog** [comment]
A new apk will be released? How this will work? Thanks

**Comment by velias** [comment]
Apk is released already in play store, should be distributed shortly

**Comment by fernandog** [comment]
Suggestion: dont clear status bar color when updating. Wait to get new status to change color.
Thanks!

**Comment by velias** [comment]
Good idea. I thought a bit about it. After refresh users expect to see current data, and this can potentionally show staled data for a while. But, on the other side, probability of status change in meantime is small, there will not be any change in most cases, so it is probably worth to implement this. Can you create new issue for this enhancement please?

**Comment by velias** [comment]
BTW is color bar enough to indicate status, or should I show status text also somewhere?

**Comment by fernandog** [comment]
Well for me is enough as I know the colors.
Donr know about the others
