### ISSUE TITLE
Force close on android 5

### ISSUE THREAD

**Issue by tobiasKaminsky** [Daskiworks/ghwatch#60]
Hello,

within the latest update of cyanogenmod 12 I get this error:
D/MainActivity(12220): Intent who runs us : Intent { flg=0x10000000 cmp=com.daskiworks.ghwatch/.MainActivity }
D/AndroidRuntime(12220): Shutting down VM
E/AndroidRuntime(12220): FATAL EXCEPTION: main
E/AndroidRuntime(12220): Process: com.daskiworks.ghwatch, PID: 12220
E/AndroidRuntime(12220): java.lang.RuntimeException: Unable to resume activity {com.daskiworks.ghwatch/com.daskiworks.ghwatch.MainActivity}: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.android.vending.billing.InAppBillingService.BIND }
E/AndroidRuntime(12220):        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2951)
E/AndroidRuntime(12220):        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2982)
E/AndroidRuntime(12220):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
E/AndroidRuntime(12220):        at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/AndroidRuntime(12220):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
E/AndroidRuntime(12220):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(12220):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(12220):        at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime(12220):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12220):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(12220):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
E/AndroidRuntime(12220):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
E/AndroidRuntime(12220): Caused by: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.android.vending.billing.InAppBillingService.BIND }
E/AndroidRuntime(12220):        at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1681)
E/AndroidRuntime(12220):        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1780)
E/AndroidRuntime(12220):        at android.app.ContextImpl.bindService(ContextImpl.java:1758)
E/AndroidRuntime(12220):        at android.content.ContextWrapper.bindService(ContextWrapper.java:538)
E/AndroidRuntime(12220):        at com.daskiworks.ghwatch.SupportAppDevelopmentDialogFragment.onCreate(SupportAppDevelopmentDialogFragment.java:83)
E/AndroidRuntime(12220):        at android.app.Fragment.performCreate(Fragment.java:2031)
E/AndroidRuntime(12220):        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:863)
E/AndroidRuntime(12220):        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
E/AndroidRuntime(12220):        at android.app.BackStackRecord.run(BackStackRecord.java:833)
E/AndroidRuntime(12220):        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
E/AndroidRuntime(12220):        at android.app.Activity.performResume(Activity.java:6030)
E/AndroidRuntime(12220):        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2940)
E/AndroidRuntime(12220):        ... 11 more

Thank you for this great app!

**Comment by velias** [comment]
Sorry @tobiasKaminsky , I was out for some time due holiday and illness. 
Login in your build of the app doesn't work as github OAuth keys are not stored in the public repository, I must keep them secure not to compromise security of github access. I'll add info about this and how to add them for your build into developer notes document later.

I'll try to prepare patched version of the app during this week and provide it to you for testing as I'm not able to reproduce bug. Seems it is present only on few Lollipop devices, which is rather strange for me.

**Comment by tobiasKaminsky** [comment]
No problem, I hope you are feeling well again!
Yeah, after rethinking about OAuth, your explanation came to my mind a couple of days ago ;)

This bug is indeed really mysterious.
Please, let me know, if I can help you.

**Comment by velias** [comment]
Hi @tobiasKaminsky , I updated Google Play Services SDK to latest version, GH::watch apk compiled against it is available at https://dl.dropboxusercontent.com/u/10683090/ghwatch-1_14-PlayServicesUpdated-unsigned.apk 
Can you test it please if it patches your problem? Thanks in advance. Vl.

**Comment by tobiasKaminsky** [comment]
I get an parsing error while installing the package and therefore I cannot install and test it

**Comment by velias** [comment]
@tobiasKaminsky try this please, contains small change in code which should help with the problem https://dl.dropboxusercontent.com/u/10683090/ghwatch-1_14-test.apk

**Comment by tobiasKaminsky** [comment]
I can confirm that it works now for me :)
Thank you very much for this great app :+1: 
I have missed it the last few days

**Comment by velias** [comment]
nice, thanks a lot for testing, going to release patched version
