### ISSUE TITLE
Tapping "unread notifications" does not show all notifications again after filter

### ISSUE THREAD

**Issue by jancborchardt** [Daskiworks/ghwatch#63]
Short: when tapping "unread notifications" after applying a repo filter, all unread messages should be shown agan.

1. Tap a specific repository to show only issues of that
2. want to go back to all unread notifications again
3. click "Unread Notifications"

Then only the sidebar gets hidden though. It's very counter-intuitive to need to tap the repo name in the sidebar again to deselect.

**Comment by velias** [comment]
You are rihgt that "Unread notifications" item in navigation drawer should reset the filter

**Comment by jancborchardt** [comment]
Thanks!
