### ISSUE TITLE
Repository filter does not show up in sidebar when in "Watched repositories" section

### ISSUE THREAD

**Issue by jancborchardt** [Daskiworks/ghwatch#64]
That's a bit confusing since the sidebar changes. The "Filter by repositories" entroes should be there all the time. Otherwise you need to click twice to get there.

**Comment by velias** [comment]
I consider "watched repositories" view as completely separate, it even contains list of repositories in main area, so showing repository filter which relates to unread notifications in sidebar on this view is meaningless for me. I can imagine to show sidebar there, but use it to contain list of organizations for watched repositories, and allow to filter watche repositories by organizations, which may be usefull for user with lots of watched repositories.

**Comment by velias** [comment]
"Filter by repositories" moved out of navigation drawer in Material design, so this isssue is obsolote now.
