### ISSUE TITLE
Sorting of "Filter by repository"

### ISSUE THREAD

**Issue by jancborchardt** [Daskiworks/ghwatch#65]
Currently the sidebar sorting is not really obvious. Seems neither alphabetically nor by number of issues.

Github itself sorts it by number of issues, that's what we should do too.

**Comment by velias** [comment]
Current sorting is by date of notification, repo with most recent notification is at top.

**Comment by jancborchardt** [comment]
Ok, that's not obvious. As I said abobe we should probably adopt the Github way of sorting, by number of issues.

**Comment by velias** [comment]
I agree this sorting is not obvious, but it doesn't mean it is wrong ;-) 
I used this sorting as github groups notifications by repositories in its https://github.com/Daskiworks/ghwatch/notifications page main area, and repository with most recent notification is on top (at least I think it is this order).
I don't think sorting by number of notifications (which is used in the github's page left sidebar) is better in any way. 
If I think about sidebar as navigation point then alphabetical sorting may give a bit more sense maybe, as user can simply find what he is looking for if there is lots of items.
But at the end, for smaller number of items there, each of these  three types of sorting is nearly equal I think, so I'm not sure if change will bring any improvement.

**Comment by jancborchardt** [comment]
Well, I’m also not sure which sorting makes more sense. Sorting a whole repo by the time of the _last_ notification seems off though.

So when in doubt it’s best to align with the system we’re designing for, which in this case is https://github.com/notifications – and they sort the repos by number of notifications/issues.

**Comment by velias** [comment]
OK, I did it this way. But order of repos with same number of notifications is not exactly same, I have no idea how they  sort them on github
