### ISSUE TITLE
Authentification fails on new device

### ISSUE THREAD

**Issue by tsdh** [Daskiworks/ghwatch#74]
I just got a new phone (Moto X Play) and when setting up gh:watch there, I always get this authentication error:

  "Communication with GitHub server failed due authentication problem. Check your account settings please."

In Perferences > GitHub user account  I have entered by user name (tsdh) and my github password.  I validated that I entered the correct password.  I also tried setting my API token as password but then it complains the user/password would be incorrect.

What else could be the problem?  The app worked great on my old phone with the same Android version (5.1.1).

**Comment by velias** [comment]
Hi, i just noticed this problem too. Temporary solution is to visit guthub.com and in user profile remove old token for GH::watch application. Then you can authenticate agai from the app.

**Comment by tsdh** [comment]
Indeed, that works.  Thanks!
