### ISSUE TITLE
Bigger notification list item menu button

### ISSUE THREAD

**Issue by Nodd** [Daskiworks/ghwatch#78]
The menu button in the notification list on the bottom right of each issue does not touch the border of each item. That means that's it's way to easy to missclick and load the issue rather than showing the menu.
Is it possible to make the button take the whole corner, without any margin ?

This problem is amplified on my phone because the touch detection on the borders of the screen is a bit off. A bigger button would really help.

**Comment by velias** [comment]
Thanks for the feedback. I'll try to extend clickabke area evaluated as the button click.

**Comment by velias** [comment]
Button height increased from 32dp to 35dp (to be same as repo image) and width to 38dp instead of right marin (which was 6 originaly)
