### ISSUE TITLE
More control on new notification checking scheduling

### ISSUE THREAD

**Issue by velias** [Daskiworks/ghwatch#8]
Allow better scheduling for new notification checking - for example do not perform it during night not to wake you up by notification sound, another checking period when WiFi  connection is available etc.

**Comment by velias** [comment]
check on wifi only is covered in #94

**Comment by laughedelic** [comment]
> for example do not perform it during night not to wake you up by notification sound

While it's good to be able to setup an application to work on a schedule, I think this is wrong reasoning: users have "Do not disturb" mode built in the OS, it's not the applications concern when to send notifications. If I'm awake at 3am and working I want to see notifications, if I don't I turn off the sound or switch profile or whatever, but the application should deliver what it's made for: notifications.

**Comment by velias** [comment]
I agree that app should not introduce own settings if android system itself provides reasonable feature. And it is case of "do not disturb during night" now, I do not plan to implement it anymore.
