### ISSUE TITLE
Show only one repository

### ISSUE THREAD

**Issue by tobiasKaminsky** [Daskiworks/ghwatch#80]
Currently I have 250 unread issues on github in several repos.
On my mobile phone I am only interested in one specific. 
As the fetch limit seems to be 50 I only get a few issues of this repo.

Is there a way to have this permanent being filtered on one repo?

**Comment by velias** [comment]
Hi Tobias. I checked that github API contains method to read notifications for one repository only, so it should be possible to implement this feature. 
From app GUI point of view, I can introduce top level config option `Default repository visibility` with values `Visible` and `Invisible`. Then user will be able to overwrite this for each repository from `Watched Repositories` view. This is probably most simple and flexible config option. When only one repo will be enabled then I'll use optimized API call to get notifications for this one repo only. Hope this works for you.

**Comment by tobiasKaminsky** [comment]
@velias is there something I can help you with?

**Comment by velias** [comment]
Send me some free time? ;-) Just kidding, ping me occasionally until finished to claim my attention and motivate me a bit. Today I wa able to write configuration part of code, so next step is use of the config in business logic :-D

**Comment by tobiasKaminsky** [comment]
Cool 👍 
Looking forward to it :-)

**Comment by velias** [comment]
Feature is implemented, I'll try to do release soon. BTW looks like github REST API started to use Link header for data paging, I created #85 to add support for this to show all data in the app
