### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [Daskiworks/ghwatch#82]
Could the `.apk` be published on Github for those who cannot or want not to depend on Google Play? Easiest was would be via Github releases, see [Creating Releases](https://help.github.com/articles/creating-releases/).

**Comment by Bluscream** [comment]
True

**Comment by IzzySoft** [comment]
@Bluscream I was thinking about [my F-Droid compatible repo](https://android.izzysoft.de/repo) – but yes, that was the idea :innocent:

**Comment by Bluscream** [comment]
Is there some documentation on how to create and sign a fdroid repo?

**Comment by IzzySoft** [comment]
@Bluscream that's a different issue :stuck_out_tongue_winking_eye: but yes, there is. In the F-Droid documentation even ([Simple Binary Repository](https://f-droid.org/manual/fdroid.html#Simple-Binary-Repository)). Or see the some blog article at the Guardian Project: [Setting up your own app store with F-Droid](https://guardianproject.info/2013/11/05/setting-up-your-own-app-store-with-f-droid/).

I felt it a good idea to set up one such repo and collect `.apk` files from Github projects. For one, to save the devs the task (so they can concentrate on improving their resp. apps), and for the other to save users from having to add hundreds of independent repos, one per app they want to use :innocent:

For details on my repo and how I deal with it, please [see here](https://android.izzysoft.de/repo/info).

**Comment by IzzySoft** [comment]
Any answer to this, @velias ? Takes less than a minute at each release, as my initial link shows.

**Comment by velias** [comment]
Done, release steps extended not to forget it next time ;-)

**Comment by IzzySoft** [comment]
Thanks a lot, @velias – and [find it here](https://apt.izzysoft.de/fdroid/index/apk/com.daskiworks.ghwatch) now as well, so folks without Playstore can use the F-Droid client to install your app and keep it up-to-date (feel free to link there ;).
