### ISSUE TITLE
Show notification title in notification

### ISSUE THREAD

**Issue by m1guelpf** [Daskiworks/ghwatch#84]
Show more info instead of [New notifications aviable]

**Comment by velias** [comment]
Thanks for your idea. I believe I'm showing real notification title in Android notification when there is only one unread notification available on Github. But if there are more unread notifications on github (even if only one is really new for android) I show general title informing you that you have more unread notifications on github. 
I'll think about extension of my app to detect number of new notifs for android to show them better.

**Comment by velias** [comment]
And BTW when there are more unread notification and I show [New notifications avaible] title then I use "Inbox Style" notification which contains info about all individual notifications (similar as used by Gmail app). Then it depends on concrete Android version how it is shown. I'll review notification style during upgrade to Material Design to see if something better is available now.

**Comment by laughedelic** [comment]
> I use "Inbox Style" notification which contains info about all individual notifications (similar as used by Gmail app)

Unfortunately it doesn't work like with Gmail notifications. Gmail groups notifications, but you can expand so see them all as if they were independent notifications and expand further each of them to read some part of the email. With ghwatch it's just one notification. I'm using Android 7.1.2

**Comment by velias** [comment]
Hmm, strange, which Android version and vendor or launcher is it? It looks a bit different on my phone.

**Comment by laughedelic** [comment]
* Phone: Xiaomi Mi 5
* Lineage OS 14.1 (Android 7.1.2)
* Nova Launcher (but I think that it doesn't influence notifications appearance)

How does it look for you?

**Comment by velias** [comment]
I see it unfolded by default. I can't paste image just now, will do tomorrow.

**Comment by velias** [comment]
@laughedelic  This is screenshot from my Xperia phone with Android 7.1
![image](https://user-images.githubusercontent.com/473926/32331717-ecdfb528-bfe3-11e7-901f-ecff9ed1ac39.png)
And this from vanilla android in emulator (some 4.x version, not fully sure which I used)
![image](https://user-images.githubusercontent.com/473926/32331782-1467bc44-bfe4-11e7-9d7f-bf300b570415.png)

As you can see, the notification is unfolded by default, at least when it is at the first position. But it may probably depend on concrete android clone (and maybe Android version, I remember some presentation from Google.io where they described how they change notifications viewing). I tried to google some info how Lineage OS handles this but no success :-(

I use common [Android Notification Inbox Style](https://developer.android.com/reference/android/app/Notification.InboxStyle.html) currently. Looks like Gmail app doesn't use it anymore, but now uses fully customized notification layout. But it may be far more complicated to implement it correctly for all devices, not sure if I'm able to do and test it correctly with my limited resources :-(

Do you think it should be helpful to at least add number of new notifications into common title? Something like `3 new GitHub notifications available` or even with number of repos they come from `3 new GitHub notifications from 2 repos available`.

**Comment by laughedelic** [comment]
> Looks like Gmail app doesn't use it anymore, but now uses fully customized notification layout. But it may be far more complicated to implement it correctly for all devices, not sure if I'm able to do and test it correctly with my limited resources :-(

OK, I found what's it called: [Bundled notifications](https://blog.stylingandroid.com/nougat-bundled-notifications/). It's a standard feature in Nougat (see [SDK docs](https://developer.android.com/guide/topics/ui/notifiers/notifications.html#bundle)). Do you think you can try to use it instead of Inbox-style? 

> Do you think it should be helpful to at least add number of new notifications into common title? Something like 3 new GitHub notifications available

In my opinion this title is completely non-informative either way. I would prefer not to see it at all: I see `GH::watch` header and the logo, so I know that it's about Github notifications. I also don't see much point in knowing how many notifications I have: I know that I have a lot anyway, so I'm more interested in seeing at a glance whether I got some important/interesting ones. This is why I want to unfold them and see the details (and also "mark as read" or "mute thread", but that's another story...)

**Comment by velias** [comment]
@laughedelic  thanks a lot, I somehow missed "Bundled notifications" support in API. You are right, it makes sense to implement them for Nougat+ . But we should keep "Inbox style" for an older android versions as behavior of Bundled is not very good for them.

**Comment by laughedelic** [comment]
Cool 👍

**Comment by velias** [comment]
I have basic implementation of Bundled notifications. Based on my tests it looks like it is possible to show only 49 individual notifications (plus one main grouping) this way (other are lost even if fired by the app).
Now I'm trying to implement reasonable actions. Proposal is this, we will see what is possible:
Click on folded notification should open GH::watch. 
When unfolded then for each individual notification:
- click on notification itself should directly open notification detail (in external app/browser)
- additinal action "Mark as read"  
- additional action "Mute thread"

**Comment by laughedelic** [comment]
@velias awesome! The actions you propose are exactly what I [had in mind](https://github.com/Daskiworks/ghwatch/issues/84#issuecomment-341549346) 👍

**Comment by velias** [comment]
This is how it looks like :-)
![obrazek](https://user-images.githubusercontent.com/473926/32952300-20c65d54-cbad-11e7-9ad7-420e32a0b1e0.png)

**Comment by laughedelic** [comment]
@velias nice! 
One suggestion: I think that original "Mute thread" is a better title for the action, another alternative is "Unsubscribe" or, if you insist on "Unwatch", I suggest at least to remove "on Github" part, because it's kind of obvious.

**Comment by velias** [comment]
@laughedelic you are right, I used bad title ☹️ I will patch it in next version, ideally use same title which github uses currently
