### ISSUE TITLE
No notifications from Private Repositories. 

### ISSUE THREAD

**Issue by CodeForCoffee** [Daskiworks/ghwatch#86]
- Account with 40 private repositories.
- worked on initial login.
- Account is using two-step Authentication.  
- Samsung S7.

**Comment by velias** [comment]
It is possible that your organization uses third-party app restrictions as documented in

**Comment by CodeForCoffee** [comment]
That was the problem. Thank you for your help.

**Comment by velias** [comment]
Yw, your rating or review in Google Play is appreciated
