### ISSUE TITLE
Release type notification click doesn't work

### ISSUE THREAD

**Issue by Bluscream** [Daskiworks/ghwatch#87]
![](https://puu.sh/v1hp4/d4e2f3ef1c.png)

**Comment by velias** [comment]
Hi, is the problem permanent or occasional or rare? Which action triggered the error please? I'm asking as everything works for me and I do not have other reports about the problem from other users.

**Comment by Bluscream** [comment]
I have this on every release when clicking on the notification, instead of opening the app (OctoDroid) or the browser with the page of the release

**Comment by velias** [comment]
Thanks, I see. I probably never had a notification for Release. I'll try to simulate this problem for me to see how JSON data from REST API looks like for the Release.

**Comment by Bluscream** [comment]
Thank you :)

**Comment by velias** [comment]
I found unsafe read of "state" JSON field in source codes, which should be the cause. Will patch it.

**Comment by Bluscream** [comment]
Awesome :3

**Comment by velias** [comment]
Any idea how to create notification for Release? Which action on github creates this notification type?

**Comment by Bluscream** [comment]
Having a new release created that is not yours or from any of your organizations and that you're watching.

**Comment by Bluscream** [comment]
A good thing that we have your app installed, way faster repsond times than *anywhere* else :D

**Comment by velias** [comment]
Thanks a lot. It's good to see it is useful.

**Comment by velias** [comment]
Look slike there was another problem in URL loading, see comment in #89
