### ISSUE TITLE
Option to "mark as read" when clicked

### ISSUE THREAD

**Issue by Bluscream** [Daskiworks/ghwatch#88]
It would be nice to have a setting that when enabled marks the clicked notification as read after the corresponding url got redirected to the system. With the current way i always have to open the app again and mark it manually after i read or responded to the notification. (Im using OctoDroid that isn't marking the current page as read when visiting)

**Comment by ADENHAM** [comment]
Jesus is LORD

**Comment by Bluscream** [comment]
True
