### ISSUE TITLE
Cannot open notification if it was a new commit to PR.

### ISSUE THREAD

**Issue by AudriusButkevicius** [Daskiworks/ghwatch#89]
If there was a comment on a PR or issue, it works fine. 
If the notification is generated by a new commit in a pull request, you get same error as #87.

**Comment by velias** [comment]
Sry, I was not able to release patch for #87 yet, itis probably same problem. Will try to release it ASAP.

**Comment by velias** [comment]
After some investigation I found other problem. Github REST API sometimes returns 'null' String instead of null value, so I improved response parsing a bit to workaround this ;-)

**Comment by AudriusButkevicius** [comment]
tyvm
