### ISSUE TITLE
Implement Dark theme

### ISSUE THREAD

**Issue by velias** [Daskiworks/ghwatch#90]
Possibility to select Dark theme for the app. Maybe also possibility to automatically switch scheme in Addroid platform supports this (not sure if it is ther elaready)

**Comment by Bluscream** [comment]
Sorry but if this isn't implemented in the next version, im gonna uninstall gh::watch

**Comment by velias** [comment]
Ok, looks like you just postponed next release untill I find enough time to impement the dark theme 😉

**Comment by Bluscream** [comment]
Thats nice :3

**Comment by velias** [comment]
@Bluscream will release soon. You owe me a beer ;-)

**Comment by Bluscream** [comment]
Sure thing !

**Comment by velias** [comment]
Hmm, filter by repository bottom sheet doesn't have correct colors in dark mode :-(

**Comment by velias** [comment]
This article helped me to find solution
https://stackoverflow.com/questions/41677477/bottomsheetdialogfragment-sets-wrong-background-color-for-dark-theme

**Comment by velias** [comment]
@Bluscream released, enjoy

**Comment by Bluscream** [comment]
Lol ur a l(eye)fesaver

![](https://gyazo.com/d5ad63cc96ca5cdef799f9a83e940c76.png)
![]()

**Comment by Bluscream** [comment]
![](https://gyazo.com/81f3361494d50682f41e71bdc7afbb25.png)

Do you have paypal? Trying to "buy you a coffee" brings up luck patcher x'D

---
Sent from my Lenovo TAB 2 A10-70L running Android 6.0 via OctoDroid v4.2.1

**Comment by velias** [comment]
@Bluscream :-D paypal.me/VlastimilE

**Comment by Bluscream** [comment]
![grafik](https://user-images.githubusercontent.com/3318223/33656573-bb51b7e2-da76-11e7-8565-1db0557f9599.png)

got ya covered 👍
