### ISSUE TITLE
UI bug: filter by repository

### ISSUE THREAD

**Issue by laughedelic** [Daskiworks/ghwatch#96]
Related to #3. 

### Steps to reproduce

1. Open the repo filter
2. Scroll to the bottom
3. Try to scroll back to the top

### Problem 

- Once at the bottom of the repo list I cannot scroll back, when I try to scroll, it's pulling the whole filter view (i.e. closing it)
- Once I close it, the notifications list that was behind it stays faded until I tap anywhere

### Expectation

- I should be able to scroll back and forth 
- It should pull the filter view only when I'm at the top of the repositories list

----

Tell me if you can't reproduce it, I'll attach screenshots.

**Comment by velias** [comment]
Thanks for the report. I noticed problem with stayed fading also. I must say I'm a bit sad of BottomSheetDialogFragment from android design library. One should expect it is easy ti use and works correctly, which is not a case.

**Comment by velias** [comment]
A bit of hacking and it looks to be resolved. Problem persists only if part of the first list item stays visible. But this is a price to allow dialog dismiss by swiping down when the list is at the top or fully rendered.
