### ISSUE TITLE
Use gzip compression for GitHub REST API call

### ISSUE THREAD

**Issue by velias** [Daskiworks/ghwatch#97]
Check if http client used to call REST API handles `Accept-Encoding: gzip` request header to save network bandwidth by default. Implement the compression if not used.

**Comment by velias** [comment]
BTW size of one notification info in list of notification v3 REST response is about 5kB!

**Comment by velias** [comment]
gzip compression implemented, looks like it may save lots of bandwidth. For my new notifications API call with about 70 notifications returned it decreases wire thansferred size from 258kB to 16kB!

**Comment by laughedelic** [comment]
Cool! 👏
